### ISSUE TITLE
Dect!210 Temperature?

### ISSUE THREAD

**Issue by ozett** [dnknth/node-red-contrib-fritzapi#10]
How do it get the temperature readings from a fritzdect 210?
if i use the temperature-node, i get a temp-reading, but suprisinglig without selecting a device with ain or control-selection. 

a Bug?

![image](https://user-images.githubusercontent.com/5937811/71421502-873d5d00-267b-11ea-9163-7fa2e3fdb574.png)

![image](https://user-images.githubusercontent.com/5937811/71421528-adfb9380-267b-11ea-9f2f-eec7ce878082.png)

**Comment by dnknth** [comment]
The topic in your debug messages looks like an AIN.

As per documentation:

`ain` string
Device identification (AIN). If both `ain` and `topic` are provided, `ain` has precedence.

`topic` string
Device identification (AIN). If both `ain` and `topic` are provided, `ain` has precedence.

Does this answer your question?

**Comment by ozett** [comment]
I will Check that next week, when Back from Holidays...now: thx for replying, i will Report my Check
