### ISSUE TITLE
Allow to set SSL Port

### ISSUE THREAD

**Issue by HDemn** [dnknth/node-red-contrib-fritzapi#11]
I'm using SSL to  access the Fritzbox. Is it possible to add the ability to set the SSL port equivalent to node-red-contrib-fritz  ?

![Fritzbox config node](https://user-images.githubusercontent.com/59763960/72203304-478fb700-346a-11ea-9e4f-6f21498f5adc.png)
.

**Comment by dnknth** [comment]
You can add the port to the connection URL, e.g. https://fritz.box:8443/.
