### ISSUE TITLE
Unknown device for Fritz!DECT 200

### ISSUE THREAD

**Issue by chris007de** [dnknth/node-red-contrib-fritzapi#14]
Today, I wanted to include a Fritz!DECT 200 in my flow. I already got a thermostat working.
I retrieved the outlets' AIN and put it as msg.ain for a outlet node with action "getState". When running the action, it outputs 
`unknown device: 116300185337`
So it obviously does not find or cannot access this AIN. It's the same behavior for any other action of the outlet node. I checked the AIN for correctness multiple times.

I am using the latest version of node-red-contrib-fritzapi (0.2.11).

Did I miss something? Is there any more debug output I could provide?

Here's the output of the getDevices action:
```
{"identifier":"116300185337","id":"17","functionbitmask":"35712","fwversion":"04.16","manufacturer":"AVM","productname":"FRITZ!DECT 200","present":"1","txbusy":"0","name":"FRITZ!DECT 200 #2","switch":{"state":"0","mode":"manuell","lock":"0","devicelock":"0"},"simpleonoff":{"state":"0"},"powermeter":{"voltage":"228641","power":"0","energy":"67"},"temperature":{"celsius":"170","offset":"0"}}
```

**Comment by chris007de** [comment]
Nevermind, I logged into the Fritzbox to check if everything is set up correct, now it works without any changes. Thanks anyway :)

**Comment by dnknth** [comment]
This could be a timing issue. When node-red loads `node-red-contrib-fritzapi`, it queries the device list from the Fritz!Box. While this happens, `unknown device` messages are logged on `stdout`.  However, after a few seconds, it should work as expected.
