### ISSUE TITLE
"Get battery charge" not working

### ISSUE THREAD

**Issue by l33tCod-er** [dnknth/node-red-contrib-fritzapi#17]
On:
FritzBox 7490, Version 07.21
Thermostat FRITZ!DECT 301, Version 04.94
Action "Get Battery Charge" is not working: "getBatteryCharge failed" when being injected
Version of node-red-contrib-fritzapi: 0.2.11

Core FritzApi returns correct value however (tried via ObjectOriented API)

If I find the time, I'll look into it myself: If you have a clue / hint, let me know!

Best,
M.

**Comment by dnknth** [comment]
Sorry, I cannot test this as I do not own a Fritz!Dect 301 device. However, 0.2.11 is a bit outdated, the latest on NPM is [0.2.14](https://www.npmjs.com/package/node-red-contrib-fritzapi). I've updated the version on [flows.nodered.org](https://flows.nodered.org/node/node-red-contrib-fritzapi), could you give it a try?

**Comment by l33tCod-er** [comment]
Updating the version resolved it. Sorry for having been aware of the new version - thought I was up-to-date!

**Comment by dnknth** [comment]
My mistake. flows.nodered.org used to auto-update from NPM, but now node maintainers must manually enable new versions. I was not aware of this change, thank you for pointing me in the right direction.
