### ISSUE TITLE
getBasicDeviceStats failed

### ISSUE THREAD

**Issue by hjboehle** [dnknth/node-red-contrib-fritzapi#18]
First of all thanks for the very helpful nodes for homeautomation. 

In my configuration I have a problem with the action "Get Basic Device stats as XML" (getBasicDeviceStats). Here my configuration:

- Fritz!Box 7390 with os 6.86
- 8 Comet DECT HKRs with firmware version 3.68

For test this action I use the example json file in this repository. Other actions are working. By using the node getBasicDeviceStats I get the follow error message:

    getBasicDeviceStats failed

And I get the follow json response from the debug node:

    {
      "error": null,
      "response": {
        "statusCode": 400,
        "body": "",
        "headers": {
          "connection": "close",
          "content-length": "0",
          "content-type": "text/plain; charset=utf-8"
        },
        "request": {
          "uri": {
            "protocol": "http:",
            "slashes": true,
            "auth": null,
            "host": "fritz.box",
            "port": 80,
            "hostname": "fritz.box",
            "hash": null,
            "search": "?0=0&sid=1a2b3c4d5e6f7a8b&switchcmd=getbasicdevicestats&ain=123456789012",
            "query": "0=0&sid=1a2b3c4d5e6f7a8b&switchcmd=getbasicdevicestats&ain=123456789012",
            "pathname": "/webservices/homeautoswitch.lua",
            "path": "/webservices/homeautoswitch.lua?0=0&sid=1a2b3c4d5e6f7a8b&switchcmd=getbasicdevicestats&      ain=123456789012",
            "href": "http://fritz.box/webservices/homeautoswitch.lua?0=0&sid=1a2b3c4d5e6f7a8b&switchcmd=getbasicdevicestats&ain=123456789012"
          },
          "method": "GET",
          "headers": {}
        }
      },
      "options": {
        "url": "http://fritz.box/webservices/homeautoswitch.lua?0=0&sid=1a2b3c4d5e6f7a8b&switchcmd=getbasicdevicestats&ain=123456789012",
        "strictSSL": true
      }
    }
Is this a bug in my fritzbos environment or is this a bug in this software?

Best Regards
Hans Jürgen

**Comment by dnknth** [comment]
Works for me on a FritzBox 7560 with OS 7.12. Tested against a CometDect version 3.54 with this flow:

    [{"id":"34c5c537.ede68a","type":"fritz-thermostat","z":"2ca2fc26.ce1154","connection":"496d2444.cfd854","name":"","action":"getBasicDeviceStats","x":390,"y":2200,"wires":[["d5d64deb.c0f658"]]},{"id":"d5d64deb.c0f658","type":"debug","z":"2ca2fc26.ce1154","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":570,"y":2200,"wires":[]},{"id":"9d35f370.28fce","type":"inject","z":"2ca2fc26.ce1154","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"119590344552","payload":"true","payloadType":"bool","x":170,"y":2200,"wires":[["34c5c537.ede68a"]]},{"id":"496d2444.cfd854","type":"fritz-api","name":"fritzbox","host":"http://fritz.box","strictSSL":true}]

Node-Red has version 1.2.5, `node-red-contrib-fritzapi` is at 0.2.14.

**Comment by hjboehle** [comment]
I tried your flow above and I get with my fritzbox credentials and with my Comet DECT ain the same error message and the same json response. My Node RED has version 1.2.5 and my node-red-contrib-fritzapi is at 0.2.14 too.

**Comment by dnknth** [comment]
Sorry, no clue. Works for me with that flow. My best guess is that the FritzOS version might make a difference.

**Comment by hjboehle** [comment]
I just did some more research and read the documentation of the AHA API. 

- [AVM Home Automation HTTP Interface](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf)

And there are bad news for me. The service "getbasicdevicestats" are offered for FritzOS greater or equal with 6.98. My Fritz!Box 7390 has the newest update with FritzOS 6.86.

I think I need a new Fritz!Box.
