### ISSUE TITLE
Can't login to Fritz!Box 6490 Cable (kdg)

### ISSUE THREAD

**Issue by cYnd** [dnknth/node-red-contrib-fritzapi#19]
Hi,

I got a very simple flow running, which should read the power and energy consumption of my DECT200 outlet:
(I am fairly new to node red, please excuse if I mistake some wording of the particular components of node red)
`[
	{
		"id": "e3fc17b2.d12928",
		"type": "tab",
		"label": "Read DECT200 Data",
		"disabled": false,
		"info": ""
	},
	{
		"id": "1481e03d.a4aea",
		"type": "inject",
		"z": "e3fc17b2.d12928",
		"name": "Set ain",
		"props": [
			{
				"p": "ain",
				"v": "08761 0030817",
				"vt": "str"
			}
		],
		"repeat": "",
		"crontab": "",
		"once": false,
		"onceDelay": 0.1,
		"topic": "",
		"x": 110,
		"y": 40,
		"wires": [
			[
				"bfe67fb7.068ff"
			]
		]
	},
	{
		"id": "bfe67fb7.068ff",
		"type": "fritz-outlet",
		"z": "e3fc17b2.d12928",
		"connection": "4843b07f.c67c3",
		"name": "Get power",
		"action": "getSwitchPower",
		"x": 270,
		"y": 40,
		"wires": [
			[
				"7477c977.b61818"
			]
		]
	},
	{
		"id": "7477c977.b61818",
		"type": "debug",
		"z": "e3fc17b2.d12928",
		"name": "",
		"active": true,
		"tosidebar": true,
		"console": false,
		"tostatus": false,
		"complete": "false",
		"statusVal": "",
		"statusType": "auto",
		"x": 450,
		"y": 40,
		"wires": []
	},
	{
		"id": "4843b07f.c67c3",
		"type": "fritz-api",
		"name": "Fritz!Box",
		"host": "192.168.178.1",
		"strictSSL": false
	}
]`

Everytime I deploy the flow, I see that the login failed and the debug message "0000000000000000".

However when I use the node-red-contrib-fritz, the login succeeds and I know that my credentials I am using are working.

Any ideas how to debug this and to get the login working?

FRITZ!OS 07.20
FRITZ!Box 6490 Cable (kdg)
NodeRed running on UnRaid 6.9.1 in docker as host container
FRITZ!DECT 200 Version 04.16

**Comment by dnknth** [comment]
"0000000000000000" is an invalid session.
Have you tried http://192.168.178.1 for the "host" setting?

**Comment by cYnd** [comment]
Yes, I also tried http://192.168.178.1 (and without http) with the same result: "0000000000000000" as message and login failed.

**Comment by cYnd** [comment]
Any other suggestions how to solve this?

**Comment by dnknth** [comment]
Well, I do not see any credentials in the flow. For me it works with an empty user name and the admin password of the FritzBox. Alternatively, you could add a FB user with appropriate permissions. Also not that the AIN contains a blank space which should be removed.

**Comment by cYnd** [comment]
I can assure you, that I set the credentials properly on the Edit fritz-api outlet :-)

![image](https://user-images.githubusercontent.com/5831288/114664192-a2622f00-9cfb-11eb-935e-076c668d9832.png)

I also tried both ways: Without a user name and only the password and I created a dedicated FB user with the permissions for this case. But still I can't login.

Is there any debug switch or other things I could try to get more information?

**Comment by dnknth** [comment]
Not that I know, but maybe you can find something in [fritzapi](https://github.com/andig/fritzapi).

**Comment by cYnd** [comment]
So after playing around a little bit (also nice excourse into node.js and javascript :-) ) I managed to login:
I left the user blank and used the password I use to connect to the FB from my home network.

Seems that the user I created didn't had the correct permissions (though I set it all permissions except for the connection from the internet).

Thanks anyways!
