### ISSUE TITLE
Temperature: Offset difference

### ISSUE THREAD

**Issue by station7** [dnknth/node-red-contrib-fritzapi#2]
The temperature received via node-red-contrib-fritzapi differs by the offset from the temperature shown in the WebIF of the Fritz!Box (which already deducted the offset), so it seems as if the offset is deducted twice.

**Comment by Multiplexer2017** [comment]
Edit line 190 in fritz.js:
before:     msg.payload = +device['temperature'].offset / 10.0 + t;
after:        msg.payload = t;

my FritzOS V7.01

**Comment by station7** [comment]
Thanks your note, mate. I helped myself by deleting the entire additonal function and reduced the getTemp- code to a simple "case 'getTemperature':" just like the other queries which works for me. But I do not know yet, whether this produces any side-effects.

**Comment by andig** [comment]
So the FB already deducts the offset itself? Would be happy to accept a PR to clean this up.

**Comment by station7** [comment]
Hi andig, 

ich meine, dass auch hier der Bug in node-red-contrib-fritzapi liegt (und nicht in "Deinem" fritzapi), denn ich konnte den Fehler durch eine einfache Änderung in fritz.js von node-red-contrib-fritzapi beheben. Viele Grüße!

**Comment by andig** [comment]
Super, danke!
