### ISSUE TITLE
Bitte um Rolladen Node erweitern

### ISSUE THREAD

**Issue by Ersthelfer** [dnknth/node-red-contrib-fritzapi#20]
Hallo,
könnt Ihr bitte die Palette um einen Rolladen Node erweitern. Mir selbst fehlt dafür die Programmierkenntniss, aber ich wäre bereit das für Euch zu testen und Euch zu unterstützen, wenn irgend welche Dinge ausprobiert werden müssen.

Ich bin leider vollkommen neu auf GitHub und habe keine andere Möglichkeit gefunden Euch zu kontaktieren.

Mein Kontakt wäre:  github $ät$ engel-city.de

Vielen Dank
Andreas

**Comment by dnknth** [comment]
Sorry, that's not going to happen anytime soon.
node-red-contrib-fritzapi is just a Node-RED wrapper for [fritzapi](https://www.npmjs.com/package/fritzapi) which supports bulbs, switches and thermostats. For other devices, please check with the respective vendor.

**Comment by Ersthelfer** [comment]
Für die Rolläden gibt es bereits den Code in der fritzapi. Er ist nur auskommentiert, weil vermutlich nicht getestet.

Ich hab den Programmierer mal angeschrieben...

Oder könntest Du mal eine Testversion erstellen, wo der Code einkommentiert ist und Deinen Wrapper erweitern?
Dann würde ich das Testen...

**Comment by Ersthelfer** [comment]
Ich habe die node-red-contrib-fritzapi installiert. Dort gibt es zwar kein "blind" Node, aber man kann den "bulb" Node verwenden und dort die Action "Set dimm level" verwenden um den Rolladen mit einem payload von 0 bis 255 anzusteuern.

Die Action "Set dimm level percentage" funktioniert leider nicht direkt, da die fritzapi (nicht die node-red-contrib-fritzapi) einen Programmierfehler hat und den Aufruf mit einem "setLevelPercentage failed" quittiert wird.

**Comment by Ersthelfer** [comment]
Hallo,

die fritzapi in der Version 0.12.0 unterstützt jetzt die Rolladenfunktion: setBlind (ain, blindState);

mit blindState "open", "close" und "stop"

Auch die Funktion setLevelPercentage funktioniert jetzt mit dieser Version.

Ich würde mich freuen, wenn wir zusammen die node-red-contrib-fritzapi um die Funktionen für die Rolläden erweitern können.
