### ISSUE TITLE
Examples for the other modules

### ISSUE THREAD

**Issue by vonglahn** [dnknth/node-red-contrib-fritzapi#21]
Hi there,

is it possible to provide examples for the bulb module? I can't get it working.

**Comment by vonglahn** [comment]
Hi there,

no there is no error. Everything seems to be allright. Maybe you can check my code if I provide the correct input for the node.

My "code":

`[{"id":"f92e8253.3ae608","type":"tab","label":"DECT 500","disabled":false,"info":""},{"id":"3d81bda7.654402","type":"fritz-bulb","z":"f92e8253.3ae608","connection":"e561db78.1de43","name":"Bulb","action":"setColor","x":710,"y":120,"wires":[["8b356bbb.3c8f58"]]},{"id":"19967628.8c9e72","type":"inject","z":"f92e8253.3ae608","name":"","props":[{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":"5","topic":"123456789","x":190,"y":120,"wires":[["827cc5a9.eb7d4"]]},{"id":"8b356bbb.3c8f58","type":"debug","z":"f92e8253.3ae608","name":"Bulb","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1010,"y":160,"wires":[]},{"id":"827cc5a9.eb7d4","type":"function","z":"f92e8253.3ae608","name":"AIN","func":"msg.payload = {\ncolor: \"red\",\nsaturation: 2,\nduration: 200\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":470,"y":120,"wires":[["3d81bda7.654402","156afa79.c8ddde"]]},{"id":"156afa79.c8ddde","type":"debug","z":"f92e8253.3ae608","name":"IN","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":790,"y":320,"wires":[]},{"id":"af07944c.06a8a","type":"inject","z":"f92e8253.3ae608","name":"","props":[{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":"5","topic":"123456789","x":190,"y":200,"wires":[["dac07dde.adad7"]]},{"id":"dac07dde.adad7","type":"function","z":"f92e8253.3ae608","name":"AIN","func":"msg.payload = false;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":470,"y":200,"wires":[["d3ef4e38.767408"]]},{"id":"d3ef4e38.767408","type":"fritz-bulb","z":"f92e8253.3ae608","connection":"e561db78.1de43","name":"Bulb","action":"setSimpleOnOff","x":710,"y":200,"wires":[["8b356bbb.3c8f58"]]},{"id":"e561db78.1de43","type":"fritz-api","z":"","name":"Router","host":"http://192.168.178.1","strictSSL":false}]`

**Comment by vonglahn** [comment]
I want just let you know that the "get"-nodes work but non of the set nodes. So my connection with the router is OK and the ain is correct.

**Comment by TheFoxy** [comment]
Hi  "Get device list" on  fritz-thermostat
send following values :

identifier: "119610751056"
id: "27"
functionbitmask: "320"
fwversion: "03.54"
manufacturer: "AVM"
productname: "Comet DECT"
present: "1"
name: "Wohnzimmer"
battery: "70"
batterylow: "0"
temperature: object
celsius: "225"                               ???????
offset: "0"
hkr: object
 tist: "45"                                    ???????
 tsoll: "43"                                  ???????
 absenk: "36"                             ???????
 komfort: "44"                            ???????
 lock: "0"
 devicelock: "0"
 errorcode: "0" 
 windowopenactiv: "0"
 batterylow: "0"
 battery: "70"
nextchange: object
summeractive: "0"
holidayactive: "0"

all values are wrong - maybe there is an offset? 
regards

**Comment by dnknth** [comment]
Hi @vonglahn, 
Your flow looks fine but sorry, I cannot test this. Since the bulb support was [contributed](../pull/13), maybe you should check with the author?

**Comment by vonglahn** [comment]
I got it working and it was (of corse) somehow my fault. The ain that the fritzbox displayed me was like that: xxxxx-xxxxxxx. But when I used the "get"-node the ain was like that: xxxxx-xxxxxxx-1. I don't know where the -1 comes from but it works with it.

Thanks for your help
