### ISSUE TITLE
Blind controll

### ISSUE THREAD

**Issue by Donni1966** [dnknth/node-red-contrib-fritzapi#23]
Hi, i try to use the blind controls and i have installed a dec controlled 

{"_msgid":"58082a12.a67394","ain":"142760444622","action":"setLevelPercentage","payload":30}

but nothing happen. 

or i try to setBlind and get this
`{"error":null,"response":{"statusCode":500,"body":"","headers":{"cache-control":"no-cache","connection":"close","content-length":"0","content-type":"text/plain; charset=utf-8","expires":"-1","pragma":"no-cache","x-frame-options":"SAMEORIGIN","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff","content-security-policy":"default-src 'none'; connect-src 'self'; font-src 'self'; frame-src https://service.avm.de https://help.avm.de https://www.avm.de https://avm.de https://assets.avm.de https://clickonce.avm.de http://clickonce.avm.de http://download.avm.de https://download.avm.de 'self'; img-src 'self' https://tv.avm.de https://help.avm.de/images/ http://help.avm.de/images/ data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-ancestors 'self'; media-src 'self'"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"fritz.box","port":80,"hostname":"fritz.box","hash":null,"search":"?0=0&sid=8da3fd97a1176593&switchcmd=setblind&t...`

The hardware is a Rollotron 1213 with DEC and Fritz Support. I can control this with the fritzen and the smart app from AVM. 

Any Idea?

**Comment by dnknth** [comment]
Hello @Donni1966, I cannot test this. The blind control was contributed in #20, please check with @Ersthelfer.

**Comment by Donni1966** [comment]
thanx ... was my mistake - wrong AIN - do not know that's there is a 1234 5678900-1 in the AIN to have success.
