### ISSUE TITLE
DECT200 can't be accessed

### ISSUE THREAD

**Issue by uwjhn** [dnknth/node-red-contrib-fritzapi#24]
I have a bunch of fritz thermostats running without any issues. today I added a DECT200 outlet, but it won't work. What I want to read is the power.

Could it be a problem, that the AIN starts with a "0"?

This is the error handler from the NodeRED debugging

`{"error":null,"response":{"statusCode":400,"body":"","headers":{"cache-control":"no-cache","connection":"close","content-length":"0","content-type":"text/plain; charset=utf-8","expires":"-1","pragma":"no-cache","x-frame-options":"SAMEORIGIN","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff","content-security-policy":"default-src 'none'; connect-src 'self'; font-src 'self'; frame-src https://service.avm.de https://help.avm.de https://www.avm.de https://avm.de https://assets.avm.de https://clickonce.avm.de http://clickonce.avm.de http://download.avm.de https://download.avm.de 'self'; img-src 'self' https://tv.avm.de https://help.avm.de/images/ http://help.avm.de/images/ data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-ancestors 'self'; media-src 'self'"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"fritz.box","port":80,"hostname":"fritz.box","hash":null,"search":"?0=0&sid=03995fd4f67c46ff&switchcmd=getswitchp...`

**Comment by dnknth** [comment]
Hi @uwjhn,

Your debug data shows some HTTP error but unfortunately not much else.
Did a quick test with a made-up AIN starting with `0` and got a meaningful error message that the device is unknown.
So I assume that a leading zero should work in principle.

For reference, here is my test flow:

```json
[{"id":"e3fa9588.992f2","type":"inject","z":"2ca2fc26.ce1154","name":"","props":[{"p":"ain","v":"0123456789","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"str","x":120,"y":380,"wires":[["60508612.20c158"]]},{"id":"837c2de2.80f498","type":"debug","z":"2ca2fc26.ce1154","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":430,"y":420,"wires":[]},{"id":"60508612.20c158","type":"fritz-outlet","z":"2ca2fc26.ce1154","connection":"496d2444.cfd854","name":"","action":"getSwitchPower","x":280,"y":380,"wires":[["837c2de2.80f498"]]},{"id":"496d2444.cfd854","type":"fritz-api","name":"fritzbox","host":"http://fritz.box","strictSSL":true}]
```

**Comment by uwjhn** [comment]
After restarting the server which runs nodeRED, everything works fine :)
