### ISSUE TITLE
Blinds: get_device state levelcontrol.levelpercentage always 0

### ISSUE THREAD

**Issue by neturmel** [dnknth/node-red-contrib-fritzapi#25]
This is most likely a limitation or bug in AVMs own AHA-HTTP Interface, 
but a get_device() for a blind (Rademacher DECT 1213) always returns 0 in 
levelcontrol.levelpercentage and levelcontrol.level, whereas the FRITZ!box UI shows the real values.

Percentage or absolute values can be set and blinds move to the position set, so this is more or less a cosmetic problem where the real opening level of a blind can't be seen by node-red. But automations can't rely on a state this way.

As said: I think this is no issue or bug of node-red-contrib-fritzapi itself, this is more like a search for a confirmation.

**Comment by dnknth** [comment]
Hello @neturmel,
Looking at [the code](../blob/master/fritz.js#L443) this seems to happen either in `fritzapi` or as you already guessed on the Fritz!Box side. Since there is no [open issue](/andig/fritzapi/issues) on `fritzapi`, you are probably correct.

**Comment by neturmel** [comment]
Good News: it seems that in the current version of FRITZ!OS (7.28) this issue is fixed.
