### ISSUE TITLE
Thermostat Temperatur value is double high

### ISSUE THREAD

**Issue by frankyboy1973** [dnknth/node-red-contrib-fritzapi#28]
Hi, sorry for my English.
When i read the GetDivece or GetDiviceList the tempertures are double as high they are in real. 
tist shows 35 but in real is it 17
tsoll shows 32 but in real is it 16
![Fritzdect1](https://user-images.githubusercontent.com/46169800/141480056-b36d28ba-8722-462e-811a-5df37b0e6d09.jpg)
When i read only GetTemperture is 17,5 to real 17,5
![Fritzdect2](https://user-images.githubusercontent.com/46169800/141480320-ab0be8f4-0d92-4ef6-a8e3-434739be4140.jpg)
And why is the output in strings and not numbers?
Please can you add HK Mode?

**Comment by dnknth** [comment]
Indeed. Tried it here with the same result.

The [FritzBox API](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf) for home automation states that for `gethkrtsoll`, `gethkrkomfort` etc. the temperature is given in steps of 0.5 °C. While the API lacks descriptions on `getdevice` and `getdevicelist` values, it is safe to assume that they use the same scale. Just multiply by 0.5 to get the correct temperature, e.g. using a JavaScript function.

As such, this seems not to be an error in `node-red-contrib-fritzapi` or `fritzapi`, but just the way how AVM designed it.

**Comment by frankyboy1973** [comment]
OK, thank you.
So i can use this in a funktion Node:
`msg.payload = msg.payload.hkr.tsoll * 0.5
return msg;`

**Comment by dnknth** [comment]
Yes, but more correctly:

   msg.payload = msg.payload.hkr.tsoll * 0.5;
   return msg;

...or use the `getTempTarget` / `getTempComfort` / `getTempNight` calls which already do the conversion.

**Comment by frankyboy1973** [comment]
OK, i dont want to produce to much traffic. I have 6 thermostats and i want to read all information at once (get device list) and after that i want to convert and use the for me important Objekts from the msg for my heating control system in node red.
To split and change the Objekts is no problem for me. But i have a problem with the funktion node when i try to convert a Object with a number in the msg.

I tried:
`msg.payload.4.hkr.tsoll = msg.payload.4.hkr.soll * 0.5;
return msg`

but it seems the funtion node has a problem with numbers in the msg name, is there an other way to use the msg in the funktion node? Or must i change the msg name before i can use it in funtion node?

**Comment by dnknth** [comment]
If you know that `msg.payload` is an array, this should work:

```javascript
msg.payload[4].hkr.tsoll = msg.payload[4].hkr.tsoll * 0.5;
return msg;
```

So, for the message in your screenshot, you could try something like:

```javascript
for (let i in msg.payload) {
    msg.payload[i].hkr.tist = msg.payload[i].hkr.tist * 0.5;
    msg.payload[i].hkr.tsoll = msg.payload[i].hkr.tsoll * 0.5;
    msg.payload[i].hkr.absenk = msg.payload[i].hkr.absenk * 0.5;
    msg.payload[i].hkr.komfort = msg.payload[i].hkr.komfort * 0.5;
}
return msg;
```
 
Hope this helps (disclaimer: code is not tested)

**Comment by frankyboy1973** [comment]
Thank you.
`msg.payload[4].hkr.tsoll = msg.payload[4].hkr.tsoll * 0.5;
return msg;
`
works fine for me. 
But i dont understand what i can do with the other code. Must i replace i to the number of the array? Sorry, but i am not very good in JavaScript.

![Payload4](https://user-images.githubusercontent.com/46169800/141844279-94039cf7-83a3-43a4-a882-0353d8edb7de.jpg)

**Comment by dnknth** [comment]
The variable `i` in the `for` loop goes through the elements in the array by their index.
So, the snippet should adjust the output message of `getDeviceList` to proper temperatures in °C which is basically what was requested in your [original post](https://github.com/dnknth/node-red-contrib-fritzapi/issues/28#issue-1052005422)

**Comment by dnknth** [comment]
This works for me:

```json
[
    {
        "id": "366a77649923822e",
        "type": "function",
        "z": "2ca2fc26.ce1154",
        "name": "",
        "func": "for (let i in msg.payload) {\n    msg.payload[i].hkr.tist = msg.payload[i].hkr.tist * 0.5;\n    msg.payload[i].hkr.tsoll = msg.payload[i].hkr.tsoll * 0.5;\n    msg.payload[i].hkr.absenk = msg.payload[i].hkr.absenk * 0.5;\n    msg.payload[i].hkr.komfort = msg.payload[i].hkr.komfort * 0.5;\n}\nreturn msg;\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 460,
        "y": 280,
        "wires": [
            [
                "ac3fb9cc10950940"
            ]
        ]
    },
    {
        "id": "b0ee717b91c43ec1",
        "type": "fritz-thermostat",
        "z": "2ca2fc26.ce1154",
        "connection": "496d2444.cfd854",
        "name": "getDeviceList",
        "action": "getDeviceList",
        "x": 280,
        "y": 280,
        "wires": [
            [
                "366a77649923822e"
            ]
        ]
    },
    {
        "id": "f94a051072eff7fc",
        "type": "inject",
        "z": "2ca2fc26.ce1154",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 110,
        "y": 280,
        "wires": [
            [
                "b0ee717b91c43ec1"
            ]
        ]
    },
    {
        "id": "ac3fb9cc10950940",
        "type": "debug",
        "z": "2ca2fc26.ce1154",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 630,
        "y": 280,
        "wires": []
    },
    {
        "id": "496d2444.cfd854",
        "type": "fritz-api",
        "name": "fritzbox",
        "host": "http://fritz.box",
        "strictSSL": true
    }
]
```

**Comment by frankyboy1973** [comment]
I have imported you Flow, entered my User and Password, but it does not work for me
![Payload5](https://user-images.githubusercontent.com/46169800/141847509-7f5496bf-467f-4b86-880e-e19b6d1ba417.jpg)
Here is the Output direkt from the thermostat node.
![Payload6](https://user-images.githubusercontent.com/46169800/141847719-2f1ff028-c165-45bf-a246-95ea8ec692b2.jpg)

**Comment by dnknth** [comment]
If you'd like to continue, please send the JSON output of the thermostat node as text (convert it with the `json` node before the `debug` node).

**Comment by dnknth** [comment]
BTW, a shorter way to write `Number(X)` is `+X`.

**Comment by frankyboy1973** [comment]
Ok, Json Node before debug Node
[{"identifier":"119600221368","id":"17","functionbitmask":"320","fwversion":"03.68","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Heizung Küche","battery":"100","batterylow":"0","temperature":{"celsius":"170","offset":"-15"},"hkr":{"tist":"34","tsoll":"30","absenk":"30","komfort":"36","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0","boostactive":"0","boostactiveendtime":"0","batterylow":"0","battery":"100","nextchange":{"endperiod":"0","tchange":"36"},"summeractive":"0","holidayactive":"0"}},{"identifier":"119600808296","id":"19","functionbitmask":"320","fwversion":"03.68","manufacturer":"AVM","productname":"Comet DECT","present":"1","txbusy":"0","name":"Heizung Wohnen","battery":"20","batterylow":"0","temperature":{"celsius":"205","offset":"-20"},"hkr":{"tist":"41","tsoll":"34","absenk":"34","komfort":"40","lock":"0","devicelock":"0","errorcode":"0","windowopenactiv":"0","windowopenactiveendtime":"0",...

Ok, next time i use +x

**Comment by dnknth** [comment]
Sorry, this is not complete (see the … at the end?)

**Comment by frankyboy1973** [comment]
Yes, i can see the ...
but how can i show it
![Payload7](https://user-images.githubusercontent.com/46169800/141858605-7885fa86-9070-4980-ba01-86d0b7472e97.jpg)
?

**Comment by dnknth** [comment]
Sorry, no idea. Apparently, the `debug` node truncates the output.
However, this issue is not about a software bug any longer, I suggest to stick with your [original](https://github.com/dnknth/node-red-contrib-fritzapi/issues/28#issuecomment-969282505) work-around.

**Comment by frankyboy1973** [comment]
yes, thats ok for me, thank you for your support.
