### ISSUE TITLE
Fritz DECT 301 : Boost function -> example not working

### ISSUE THREAD

**Issue by CityJumperAC** [dnknth/node-red-contrib-fritzapi#31]
In the current implementaion the BOOST button in the example is not working for the Thermostat.
As it just sends payload:boost to the setTemp function.

By reading the Fritzapi documentation there is a "setHkrBoost" and also a "setHkrWindowOpen" function implemented.
But my current skills and time do not allow me to implement this to the node.
Also the AVM HTTP API has it implemented.

Maybe both with the "endTime" precalculated, so we can use the payload to set the time in minutes? (and 0 to disable again)

would appriciate this.

![grafik](https://user-images.githubusercontent.com/76394484/147700749-bb4330a8-838f-491f-894d-223d699f087a.png)

**Comment by dnknth** [comment]
Just help me out, what are these functions about?

**Comment by dnknth** [comment]
Oh, and what example are you referring to?

**Comment by CityJumperAC** [comment]
Ahh sorry, was not your example, I can post the code here later on.

The boost function is to set the thermostat to maximum for a defined time.

For example in the bathroom if you want to have it nice and warm. 

In the API you find it in setHkrBoost.
Basically just need to call the function with an end timestamp (counting from 1970)

**Comment by dnknth** [comment]
Right, good to know. My wife will appreciate a warm bathroom. Looking into it over the long weekend.

**Comment by CityJumperAC** [comment]
Documentation : 
![grafik](https://user-images.githubusercontent.com/76394484/147745767-e54c9a29-4375-4e48-94d6-0cbeff348fd3.png)
https://github.com/andig/fritzapi/blob/56245fb7f3bd6a5a3940d13ae9db8e9687045067/index.js#L827

![grafik](https://user-images.githubusercontent.com/76394484/147745803-7b5e7c6c-11e5-46c5-99e4-65d9de825fef.png)
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf

The example i started with : "see the boost button"
https://github.com/Nerdiyde/NodeRedSnippets/blob/master/snippets/fritz_box_control_dect_thermostat_heater.json

**Comment by CityJumperAC** [comment]
Looking good.
No issues so far. just need to push some heat in there ;-)
THY guys

**Comment by dnknth** [comment]
Hello @CityJumperAC, does it work for you? Over here I always get "setHkrBoost failed" errors after merging #32 und updating fritzapi to 0.13.0. How did you test this?

**Comment by wetzf** [comment]
I had a similar issue after updating. In my case npm installed an additional version 0.12 of fritzapi in _.node-red/node_modules/node-red-contrib-fritzapi/node-module_ 

After some headache i found that probably the dependency in [package.json](https://github.com/dnknth/node-red-contrib-fritzapi/blob/master/package.json#L7) caused the issue.  [](url)

"^0.12.0" does not allow version 0.13.0
https://github.com/npm/node-semver#caret-ranges-123-025-004

**Comment by CityJumperAC** [comment]
@dnknth  I had not this problem due to i replaced the files manually.

But @wetzf you are right, seems to be a typo error in the package, change it to ^0.x or ^0.13.x

**Comment by dnknth** [comment]
Published node-red-contrib-fritzapi@0.4.1 with #32 to NPM. Thanks for the contributions!
@wetzf and @CityJumperAC feel free to close this issue after verifying that it works as expected.

**Comment by wetzf** [comment]
Works as expected. Thank you very much!
One minor issue i noticed: SetHkrBoost and SetHkrWindowOpen appear twice in [fritz.hml](https://github.com/dnknth/node-red-contrib-fritzapi/blob/master/fritz.html#L127) and subsequently in the flows "Action" dropdown.

**Comment by dnknth** [comment]
Good catch, this is now corrected in `node-red-contrib-fritzapi@0.4.1`.
