### ISSUE TITLE
get guestWIFI

### ISSUE THREAD

**Issue by PhilW35** [dnknth/node-red-contrib-fritzapi#34]
Hi there,
I am a beginner with Node red so sorry if I ask stupidl ;-)

I changed most of my Fritz/AVM controls to your node and it works fine so far. 

The only thing that doesn't work for me ist the "get guest wifi status"
No matter what I inject, I only get a _{ empty }_ in the output (debug), and it seems that the status is not queried at all.
Am I doing something wrong?

2nd question: What is the exact Inject/input for the "set window open" and the "set boost mode" Could it be the AIN as topic and a number as payload for the minutes? And as I understand the Fritz API correct sending direct a "0" as payload the time count will stop and it goes back to normal operation 

THX for your help
Guido

**Comment by dnknth** [comment]
As to your 2nd question: Yes, the payload should be an amount of minutes, see #31.
And yes, setting it to zero minutes should resume normal mode.

Will look into guest wifi and come back later.

**Comment by PhilW35** [comment]
Good morning @dnknth ,

thx so far.
Sorry for the long text now, I have tested yesterday evening and this morning very excessively all possible commands with the thermostats.  The main functions setTemp getTemp etc. etc. work fine so far also and I can read out both in the displays and in the respective get status. So far so good. 
The functions "setWindow open" and "setBoost mode" are also sent with the specified times and I can then also read out the status correctly from "getDevice". however, nothing happens at the thermostat. Neither I see on the display the message "Window open" nor "Boostmode", and the thermostat also makes no function during the states, neither valve open nor closed. 
But as I said, in the status I see the correct feedbacks

Now, after what feels like 1000 deploys of the node, I suddenly can't get into the FritzBox via the node. Error message on all  commands "login failed".
I restarted everything.
Both a reboot of the Fritz and the node red/pi brings no improvement. The log of the Fritz also says login attempt failed, wrong password. I also changed the account and tested it. Does not work either. 

I have the node-red-contrib-fritz running in parallel (mobile presence) with the same login. The runs the whole time, and even now with the same account connection to Fritz without problems.

I hope this is not only due to my beginner errors. Maybe you have an idea

Thanks

Guido
![1](https://user-images.githubusercontent.com/9362045/148362702-fa317ab9-157e-48b9-82f9-a1944ce26788.PNG)

**Comment by dnknth** [comment]
Guest wifi is broken as per Fritz!OS 7, see andig/fritzapi#10 for a discussion. Disabled the defunct Guest Wifi node in 0.5.0

**Comment by PhilW35** [comment]
@dnknth 
 I got the answer from AVM direct that it should work:
_Wir haben nachgestellt (FRITZ!Box 7590 AX) und der Gast AP sowie der AP für 2,4 GHz und 5 GHz lassen sich über TR064 (WLANConfiguration1-3:SetEnable) aktivieren und deaktivieren. 
Bitte beachten: wenn sowohl 2,4 als auch 5 GHz AP deaktiviert sind, bleibt der Gast AP nach der Aktivierung "Disabled" (WLANConfiguration3:GetInfo Status), da mindestens einer der beiden Haupt APs aktiv sein muss. 
Falls das Problem damit nicht gelöst ist, schicken Sie uns bitte relevanten Code sowie Supportdaten Ihrer FRITZ!Box per Mail._ 

I don't know if they can use it but I'll send them the node red code. Also for the window and boost thing that still don't work.
Hope to get any help that I can share with you

**Comment by PhilW35** [comment]
For info, have now read myself and tested and verified. The setting and the status query for Guest Wifi works again under AVM OS7. The reference to andig/fritzapi#10 is not correct anymore

**Comment by dnknth** [comment]
So, can we close this?

**Comment by PhilW35** [comment]
Absolutely, yes.
