### ISSUE TITLE
Error when reading Temp

### ISSUE THREAD

**Issue by A380Coding** [dnknth/node-red-contrib-fritzapi#35]
I have a DECT200 outlet which has not been connected for a while. Since I'm reading the state and temp from all devices, I'm also doing this for the currently not connected one.
In the debug console I get a yellow error saying "getTemperature failed" and a lengthy red error message from the Fritzbox.
If I'm reading the state, I just get 0 without any error.

Of course, I can not read the temperature from a device that is currently not connected. But is there a better way to handle this? I have a catch node which triggers on each temperature read that fails.
Can I somehow check if an AIN is currently connected before triggering a read command? Or could the outlet node return some defined value instead of causing an exception?

**Comment by A380Coding** [comment]
Maybe the status code helps here:
`{"error":null,"response":{"statusCode":500,"body":"","headers":`

**Comment by dnknth** [comment]
The `thermostat` node has a `getDeviceList` method that outputs device descriptions as an array. At least for thermostats, there is a `present` attribute. Could you please check whether outlets are also listed and whether they also have presence information? I do now have a DECT200 around to test this myself.

Thanks.

**Comment by A380Coding** [comment]
They do have a present attribute and by checking that upfront I can avoid the issue above. That works for me. What is strange though, is that the there is this "red" error reading the temperature but not when reading the state. But checking presence before reading does the trick.
Thanks.

**Comment by dnknth** [comment]
OK to close this issue?

**Comment by A380Coding** [comment]
yes thanks
