### ISSUE TITLE
How to set thermostats "off"

### ISSUE THREAD

**Issue by uwjhn** [dnknth/node-red-contrib-fritzapi#36]
How do I set a thermostat to "off" state? Sending a payload of "0" sets the target temperature to 8 degrees, not "OFF". 

The API says that it could work:
"Set target temperature setTempTarget, supports 'ON'/'OFF' to enable/disable thermostat"

**Comment by dnknth** [comment]
Try "on" or "off" for the messages's `payload`.

**Comment by uwjhn** [comment]
I tried "OFF" (like it says in the API) and "Off". Unfortunately, I forgot to try the third version "off".
Long story short: It works with "off".

**Comment by dnknth** [comment]
Added a note to the README.
