### ISSUE TITLE
15minutes intervall dect301

### ISSUE THREAD

**Issue by MrThiemann** [dnknth/node-red-contrib-fritzapi#37]
hey,
Do you know if there is a way to bypass the "interval time"?
That would be extremely important, especially for `payload[1].hkr.windowopenactiv`!

I have a window sensor that should trigger this command.
It just doesn't help if I open the window to air the air, the sensor is triggered, but the thermostat only gets the command after 15 minutes that the window is open..
Of course I can avoid this by pressing "OK" on the thermostat.

Maybe you have an idea?

**Comment by dnknth** [comment]
Sorry, no clue. In fact, if impatient I also just press OK.
