### ISSUE TITLE
Question: How to send AIN?

### ISSUE THREAD

**Issue by joerk** [dnknth/node-red-contrib-fritzapi#5]
Hello, 

I am new to node-red and play with node-red-contrib-fritzapi  thermostat - node. I aways get "unknow device:" - output and then the message valid devices where my device is listed. The ain value is identical but how to send it correct. In the how-to I read 

>>> ... AIN as ain or topic on the input message

So my try is { "ain": "value"} . Please give me a hint for this beginners trouble. 

Regards Joerk

**Comment by dnknth** [comment]
Thanks @joerk for the hint.
I can reproduce this behaviour with the current version, it is probably a bug.
Will look into it.

**Comment by dnknth** [comment]
@joerk please pass in the AIN as `message.topic` or `message.ain`. If you inject `{ "ain": "value"}`, it will end up in `message.payload.ain`. It should work if you inject a timestamp with the AIN as `topic`.

The `message.payload` is used for target values in the set* or adjust* functions, they usually expect numbers or booleans, but no JSON.

If this helps, please close this issue.

**Comment by joerk** [comment]
Ok, I was not familiar with the message format. Now it is clear.
