### ISSUE TITLE
getBatteryCharge failed / getWindowOpen failed

### ISSUE THREAD

**Issue by domi-a** [dnknth/node-red-contrib-fritzapi#6]
hi,

just testet your palette in node red.
- getcurrenttemperature
- gettargettemperature
- getdaytemp 
- .. and so on
are working fine.

but 
- getBatteryCharge 
- getWindowOpen
do not work as expected.

the fritzbox configuration node error.logs: Fritz!Box session renewal failed
in both cases - while the working node types do work everytime. even right after the others have failed.

fritzos on the fritte: 7.12
thx for your work in this package

**Comment by dnknth** [comment]
Hello @domi-a,

I cannot reproduce this with version 0.2.8, `getBatteryCharge` and `getWindowOpen` work as expected with my "fritte" 7560 and OS 7.12. Can you please re-test?

**Comment by dnknth** [comment]
@domi-a: Is this still an issue?

**Comment by domi-a** [comment]
hi,
yes the behavior on my machine still exists.

the node-red-contrib-fritzapi Version is the same: 0.2.8
the fritzbox is the same with the same OS as yours: 7560, 7.12.
my node red is 1.0.1 

in all cases i'm calling your nodes with an inject node with ain as topic
one error is logged by the configuration node from the fritzbox: "Fritz!Box session renewal failed"
then a warning is logged by the same node: "getBatteryCharge failed"

not sure what i can tell you more

**Comment by dnknth** [comment]
Sorry, cannot reproduce the problem, it works for as intended for me. If you have any additional clues, please feel free to re-open the issue.

**Comment by janfwesterkamp** [comment]
For all those who have the same issue:

There is a simple solution:

> Unable to update thermostat battery charge
> 
> Battery charge is not an API function. That means that the user must have access to FritzBox 
> administration, not only to the SmartHome API in order to use this functionality. Update your
> Fritz!Box user accordingly.

Source: https://www.npmjs.com/package/homebridge-fritz
