### ISSUE TITLE
Dect!200 Internal Server Error

### ISSUE THREAD

**Issue by Frogy76** [dnknth/node-red-contrib-fritzapi#8]
It's possible to turn the Plug on but if you want to turn it off it get's this eror

"Action failed with error: 500: Internal Server Error"

**Comment by dnknth** [comment]
@Frogy76: Could you check the Node-RED logs for the error? As I do not own a DECT!200, I need some information to figure out the root cause.

**Comment by dnknth** [comment]
Closing until more information is provided. @Frogy76 feel free to re-open the issue with details on the error.
